### ISSUE TITLE
UI DESIGN IDEA

### ISSUE THREAD

**Issue by CSIYI** [nguyensjsu/fa18-202-polymorphers#12] opened 2018-11-13 21:44 UTC
How do we want to design the UI? Keep the traditional TV version, or we can design it in a modern way.

**Comment by davidpmontes** [comment] 2018-11-13 22:56
I think it would be cool to emulate the look of the modern tv show now as much as possible.

**Comment by adiosray** [comment] 2018-11-13 23:02
Let’s start with the traditional TV, Blue Black design first, which would be easy to implement. But also you could figure out a modern design pattern

**Comment by adiosray** [comment] 2018-11-13 23:03
Duplicate of #13

**Closed** 2018-11-16 23:06 UTC
